### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by c-bata** [CyberAgent/cmaes#35]
## v0.5.1

* [x] Merge https://github.com/CyberAgent/cmaes/pull/34

## ~~v1.0.0~~

* [x] Remove deprecated features (Optuna sampler and monkeypatch) (#42).
* [x] Update classifiers: `Development Status :: 5 - Production/Stable` (#43).

**Comment by c-bata** [comment]
I will release v0.6.0 for #46.
